import type { Hooks, Plugin, PluginInput, PluginModule } from "@opencode-ai/plugin"
import { tool } from "@opencode-ai/plugin"
import { loadOpenAIAuth } from "./auth"
import { callViaCodexImages, MAX_EDIT_IMAGES, SIZE_ARG_PATTERN } from "./codex"
import { resolveReferenceImages } from "./input-image"
import { saveGeneratedImage } from "./output-image"
import { createSessionImageStore } from "./session-images"

const GptImagePlugin: Plugin = async (_input: PluginInput): Promise<Hooks> => {
  const sessionImages = createSessionImageStore()
  return {
    event: async ({ event }) => {
      if (event.type === "session.deleted") {
        sessionImages.evict(event.properties.info.id)
      }
    },
    tool: {
      gpt_imagegen: tool({
        description: [
          "Generate raster images with OpenAI's gpt-image-2 model.",
          "Use for AI-created bitmap visuals such as photos, illustrations, textures, sprites, and mockups.",
          "Do not use when the task is better handled by editing existing SVG/vector/code-native assets, extending an established icon or logo system, or building the visual directly in HTML/CSS/canvas.",
          // The reference-selection guidance mirrors codex's model-facing tool description:
          // https://github.com/openai/codex/blob/9e552e9d15ba52bed7077d5357f3e18e330f8f38/codex-rs/ext/image-generation/imagegen_description.md
          "Omit both `referenced_image_paths` and `num_last_images_to_include` when generating a brand new image.",
          "For edits, use `referenced_image_paths` when every target image has a local file path; label each image's role inline in `prompt`, for example: 'Image 1: reference image'.",
          "Use `num_last_images_to_include` only when a target image has no local file path. Never provide both.",
          "For many distinct assets, invoke gpt_imagegen once per requested asset rather than relying on multi-image output; gpt_imagegen returns one image per call.",
          "Requires OpenCode to be authenticated with ChatGPT OAuth. Returns the absolute path of the saved PNG.",
        ].join(" "),
        // https://developers.openai.com/api/docs/guides/image-generation
        args: {
          prompt: tool.schema.string().describe("Description of the image to generate."),
          out: tool.schema
            .string()
            .describe("Output file path, relative to the project directory unless absolute. The plugin writes a PNG."),
          size: tool.schema
            .string()
            .regex(SIZE_ARG_PATTERN)
            .optional()
            .describe("Optional image size. Use `auto` or `WIDTHxHEIGHT`, e.g. `1024x1536`."),
          referenced_image_paths: tool.schema
            .array(tool.schema.string())
            .max(MAX_EDIT_IMAGES)
            .optional()
            .describe(
              `Optional reference image paths (at most ${MAX_EDIT_IMAGES}), relative to the project directory unless absolute.`,
            ),
          num_last_images_to_include: tool.schema
            .number()
            .int()
            .min(1)
            .max(MAX_EDIT_IMAGES)
            .optional()
            .describe(
              `Include the last N images generated by this tool in the current session as references (1-${MAX_EDIT_IMAGES}).`,
            ),
        },
        async execute(args, ctx) {
          const auth = await loadOpenAIAuth()
          if (!auth) {
            throw new Error("OpenAI ChatGPT OAuth credentials not configured.")
          }

          const recentImages = sessionImages.getRecent(ctx.sessionID)
          const inputImageDataUrls = await resolveReferenceImages(args, ctx.directory, recentImages)
          const base64 = await callViaCodexImages(auth, args, inputImageDataUrls, { signal: ctx.abort })

          const { savedPath, versioned, message } = await saveGeneratedImage(args.out, ctx.directory, base64)

          // Recorded only after a successful save so a failed call cannot enter the history.
          // The data URL format matches how codex reads past generations back from history:
          // https://github.com/openai/codex/blob/9e552e9d15ba52bed7077d5357f3e18e330f8f38/codex-rs/ext/image-generation/src/tool.rs#L379-L381
          sessionImages.record(ctx.sessionID, `data:image/png;base64,${base64}`)

          return {
            output: message,
            metadata: {
              out: savedPath,
              versioned,
              billing: "subscription",
            },
          }
        },
      }),
    },
  }
}

export default {
  id: "opencode-gpt-imagegen",
  server: GptImagePlugin,
} satisfies PluginModule
