import * as fs from "node:fs/promises"
import * as path from "node:path"
import { fileTypeFromBuffer } from "file-type"
import { MAX_EDIT_IMAGES } from "./codex"
import type { GenerateArgs } from "./types"

async function readImageAsDataUrl(filePath: string, ctxDir: string): Promise<string> {
  const abs = path.isAbsolute(filePath) ? filePath : path.resolve(ctxDir, filePath)
  // Failure wording mirrors codex's referenced-image errors:
  // https://github.com/openai/codex/blob/9e552e9d15ba52bed7077d5357f3e18e330f8f38/codex-rs/ext/image-generation/src/tool.rs#L424-L451
  let buf: Buffer
  try {
    buf = await fs.readFile(abs)
  } catch (err) {
    throw new Error(`unable to read referenced image at \`${abs}\`: ${err}`)
  }
  const detected = await fileTypeFromBuffer(buf)
  if (!detected?.mime.startsWith("image/")) {
    throw new Error(`unable to process referenced image at \`${abs}\`: unsupported image file type`)
  }
  return `data:${detected.mime};base64,${buf.toString("base64")}`
}

// Read the reference image paths and encode them as data URLs the Codex backend
// accepts as image_url content. Paths resolve relative to the OpenCode context
// directory unless absolute.
export async function readReferenceImages(paths: string[], ctxDir: string): Promise<string[]> {
  return Promise.all(paths.map((p) => readImageAsDataUrl(p, ctxDir)))
}

// Reference selection and its error contract mirror codex's request_for_call_args:
// https://github.com/openai/codex/blob/9e552e9d15ba52bed7077d5357f3e18e330f8f38/codex-rs/ext/image-generation/src/tool.rs#L259-L317
// Unlike codex, which scans the conversation history, `num_last_images_to_include`
// draws from recentImageDataUrls (newest last) — images generated by this tool in the
// current session — because the OpenCode plugin API does not expose the conversation.
export async function resolveReferenceImages(
  args: Pick<GenerateArgs, "referenced_image_paths" | "num_last_images_to_include">,
  ctxDir: string,
  recentImageDataUrls: string[],
): Promise<string[]> {
  // The bounds below are also enforced by the tool schema; the runtime re-checks are
  // kept deliberately because codex has both layers too (schemars + request_for_call_args).
  const paths = args.referenced_image_paths ?? []
  if (paths.length > MAX_EDIT_IMAGES) {
    throw new Error(`\`referenced_image_paths\` must contain at most ${MAX_EDIT_IMAGES} paths`)
  }
  const count = args.num_last_images_to_include
  if (paths.length > 0 && count !== undefined) {
    throw new Error("provide only one of `referenced_image_paths` or `num_last_images_to_include`")
  }
  if (paths.length > 0) return readReferenceImages(paths, ctxDir)
  if (count === undefined) return []
  if (!Number.isInteger(count) || count < 1 || count > MAX_EDIT_IMAGES) {
    throw new Error(`\`num_last_images_to_include\` must be between 1 and ${MAX_EDIT_IMAGES}`)
  }
  const images = recentImageDataUrls.slice(-count)
  if (images.length !== count) {
    // Deviation from codex's "conversation images" wording: the pool here is only this
    // tool's own generations in the current session, and the message should say so and
    // point at the recovery path.
    throw new Error(
      `requested the last ${count} images generated in this session, but only ${images.length} were available; ` +
        "pass `referenced_image_paths` to reference images by file path instead",
    )
  }
  return images
}
